gaia:
  dataset: 'gaia'
  data_path: 'data/GAIA_TKG'

  entity_embedding:
    input_data_path: 'EntityEmbedding/data/GAIA_TKG_t'
    failure_type: ['access_permission_denied','file_moving','memory_anomalies','normal_memory_freed_label']
    # nodes: ['webservice1', 'mobservice1', 'logservice2', 'webservice2', 'logservice1', 'dbservice2', 'mobservice2', 'redisservice1', 'redisservice2', 'dbservice1']
    nodes: 'webservice1 mobservice1 logservice2 webservice2 logservice1 dbservice2 mobservice2 redisservice1 redisservice2 dbservice1'
    RE-GCN_main: 'EntityEmbedding/src/main.py'
    hidden_dimension: 50
    window_size: 5
    gcn_layer: 2
    epoch: 50
    output_data_path: 'EntityEmbedding/output/GAIA'
    output_data_path_v: 'EntityEmbedding/output/GAIA_npz'
    output_data_path_g: 'output/GAIA_graph'
    log_path: 'EntityEmbedding/log'
    model_path: 'EntityEmbedding/models/'
    model_name: 'GAIA'
    
  graph_embedding:
    input_train_data_path: 'output/GAIA_graph/GAIA_train.npz'
    input_all_data_path: 'output/GAIA_graph/GAIA_all.npz'
    output_path: 'output/GAIA_graph/GAIA_save.npz'
    output_vector_dimension: 100
    failure_classification_number: 5
    node_dimension: 50
    epoch_num: 100

  cluster:
    input_data_path: 'output/GAIA_graph/GAIA_save.npz'
    output_data_path: 'output/GAIA_cluster/GAIA_result.csv'
    stat_output_path: 'output/GAIA_cluster/GAIA_stat.csv'
    report_output_path: 'output/GAIA_cluster/report.txt'
